#!/bin/bash
# Macでターミナルの色を変えるスクリプト
# Usage:
# chbg red
# chbg blue
# chbg green

set_term_bgcolor(){
  local R=$1
  local G=$2
  local B=$3
  /usr/bin/osascript <<EOF
tell application "iTerm"
  tell the current terminal
    tell the current session
      set background color to {$(($R*65535/255)), $(($G*65535/255)), $(($B*65535/255))}
    end tell
  end tell
end tell
EOF
}

set_profile() {
	/usr/bin/osascript -e "tell application \"Terminal\" to set current settings of first window to settings set \"$1\""
}

if [[ "$@" == red ]]; then
	set_term_bgcolor 50 0 0
elif [[ "$@" == green ]]; then
	set_term_bgcolor 0 50 0
elif [[ "$@" == blue ]]; then
	set_term_bgcolor 0 0 50
else
	set_term_bgcolor 0 0 0
fi
